"""empty message

Revision ID: 11580042ccaf
Revises: 9eb6cb04d21d
Create Date: 2024-05-10 17:13:57.330201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11580042ccaf'
down_revision = '9eb6cb04d21d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product__category', schema=None) as batch_op:
        batch_op.drop_constraint('product__category_category_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product__category', schema=None) as batch_op:
        batch_op.create_unique_constraint('product__category_category_name_key', ['category_name'])

    # ### end Alembic commands ###
