"""empty message

Revision ID: 4aaf7f640bb7
Revises: f9f239dcbf02
Create Date: 2024-05-09 08:43:42.400381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aaf7f640bb7'
down_revision = 'f9f239dcbf02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.Column('product_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_percentage', sa.Integer(), nullable=True),
    sa.Column('discounted_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('product_display_title', sa.String(length=250), nullable=True),
    sa.Column('product_description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
