"""empty message

Revision ID: 6df89183ff0c
Revises: 11580042ccaf
Create Date: 2024-05-11 19:02:38.703878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df89183ff0c'
down_revision = '11580042ccaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product__category', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['category_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product__category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
