"""empty message

Revision ID: 9eb6cb04d21d
Revises: edf3be814c3a
Create Date: 2024-05-09 10:22:38.114119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb6cb04d21d'
down_revision = 'edf3be814c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_product_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint('product_product_name_key', ['product_name'])

    # ### end Alembic commands ###
