"""empty message

Revision ID: a8a9bcfa085e
Revises: fa80905c3e5c
Create Date: 2024-11-14 08:31:09.017702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a9bcfa085e'
down_revision = 'fa80905c3e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('cart')
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',

    )
    op.create_table('cart',

    )
    op.create_table('order_items',

    )
    # ### end Alembic commands ###
