"""empty message

Revision ID: dc9e1916a3f1
Revises: 6df89183ff0c
Create Date: 2024-05-12 14:38:57.063630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9e1916a3f1'
down_revision = '6df89183ff0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product__category', schema=None) as batch_op:
        batch_op.drop_constraint('product__category_category_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product__category', schema=None) as batch_op:
        batch_op.create_unique_constraint('product__category_category_name_key', ['category_name'])

    # ### end Alembic commands ###
