"""empty message

Revision ID: edf3be814c3a
Revises: 4aaf7f640bb7
Create Date: 2024-05-09 08:49:44.695207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf3be814c3a'
down_revision = '4aaf7f640bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_category', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'product__category', ['product_category'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_category')

    # ### end Alembic commands ###
